[font]
normal = { family = "FiraCode Nerd Font", style = "Regular" }
size = 11.0

[colors]
primary = { foreground = "#b2b2b2", background = "#000000" }
cursor = { text = "#000000", cursor = "#52ad70" }
selection = { text = "CellForeground", background = "#3f324c" }
draw_bold_text_with_bright_colors = true

[colors.normal]
black = "#000000"
red = "#cc5555"
green = "#55cc55"
yellow = "#cdcd55"
blue = "#5455cb"
magenta = "#cc55cc"
cyan = "#7acaca"
white = "#cccccc"

[colors.bright]
black = "#555555"
red = "#ff5555"
green = "#55ff55"
yellow = "#ffff55"
blue = "#5555ff"
magenta = "#ff55ff"
cyan = "#55ffff"
white = "#ffffff"

